let header = document.querySelector('header')
let styleSheet = document.createElement('link')
styleSheet.setAttribute('type', 'text/css')
styleSheet.setAttribute('rel', 'stylesheet')
styleSheet.setAttribute('href', 'style.css')
header.appendChild(styleSheet)
